### ISSUE TITLE
Mention dependence on async-trait

### ISSUE THREAD

**Issue by tbillington** [mbuczko/hugsqlx#1]
Without `async-trait` as a dependency of my project it was failing to compile with the below message. I saw the example depended on it even though it was never explicitly included so I decided to try adding it, and it fixed the compiler error.

Possibly hugsqlx should provide it, or make it explicit the user must bring it into scope in files that use the `HugSqlx` trait :)

```
error[E0706]: functions in traits cannot be declared `async`
 --> src/fun.rs:3:10
  |
3 | #[derive(HugSqlx)]
  |          ^^^^^^^ `async` because of this
  |
  = note: `async` trait functions are not currently supported
  = note: consider using the `async-trait` crate: https://crates.io/crates/async-trait
  = note: this error originates in the derive macro `HugSqlx` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared crate or module `async_trait`
 --> src/fun.rs:3:10
  |
3 | #[derive(HugSqlx)]
  |          ^^^^^^^ use of undeclared crate or module `async_trait`
  |
  = note: this error originates in the derive macro `HugSqlx` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by mbuczko** [comment]
Thanks for bringing this up. As mentioned in #2 - I'm still unsure about the general strategy around dependencies (should I enforce them in my crate or delegate it to consumers), so as for now I'm making it clear in documentation what crates HugSQLx depends on.
