### ISSUE TITLE
Windows canonical string bug on `#[derive(HugSqlx)]` macro's query path

### ISSUE THREAD

**Issue by lohvht** [mbuczko/hugsqlx#4]
# Describe the bug

On target Windows platforms, it seems that the derive macro `#[derive(HugSqlx)]` will always result in the following panic

Example minimal reproducible code, on a newly initialised cargo project with an empty `src/test_stmt.sql` file.
```
#[derive(hugsqlx::HugSqlx)]
#[queries = "src/test_stmt.sql"]
pub struct Database {}

fn main() {
    println!("Hello, world!");
}
```
The above will always produce the follow panic
```
error: proc-macro derive panicked
 --> src\main.rs:1:10
  |
1 | #[derive(hugsqlx::HugSqlx)]
  |          ^^^^^^^^^^^^^^^^
  |
  = help: message: Queries path must be relative to Cargo.toml location (D:\Users\Victor\projects\test_hugsqlx)
```

# Additional context
I'm on the following hugsqlx version
```
hugsqlx = {version = "0.1.3", features = [ "mysql" ]}
```

heres more info about my current target:
```
PS D:\Users\Victor>  rustc -vV
rustc 1.72.0-nightly (330727467 2023-06-29)
binary: rustc
commit-hash: 330727467b8fdf2c43b95095a0efae7012c4f83b
commit-date: 2023-06-29
host: x86_64-pc-windows-msvc
release: 1.72.0-nightly
LLVM version: 16.0.5
```

# Proposed Changes
I have done some digging around regarding this issue and its appears to be due to the way windows handles canonicalisation of file paths and the logic at [line 72 of hugsqlx-core/src/lib.rs](https://github.com/mbuczko/hugsqlx/blob/9a4ba3fb9b21ad37b983354b0e16bdae98d050ff/hugsqlx-core/src/lib.rs#L72)

`canonical_path` appears to be prefixed with an additional `\\?\` string during the call to `Path::new(&cargo_dir).canonicalize()`. This appears to be Window's way to disable all string parsing of its path (related docs [here](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-file-namespaces)) will lead to the `!canonical_path.starts_with(&cargo_dir_canonical_path)` check at line 73 always failing as `env::var("CARGO_MANIFEST_DIR")` doesnt seem to be canonicalised. I propose to have an additional step to canonicalise the `cargo_dir` before doing the comparison.

I don't mind working on this small fix for this over the weekend when I have slightly more time and try and retest this portion on both Linux as well as Windows to ensure that there aren't any regressions

**Comment by mbuczko** [comment]
solved in https://github.com/mbuczko/hugsqlx/pull/5 (release `0.1.4`)
