### ISSUE TITLE
Enhancement: queries path relative to both `CARGO_MANIFEST_DIR` and workspace root.

### ISSUE THREAD

**Issue by lohvht** [mbuczko/hugsqlx#6]
Hi! As the title suggests, I would like propose a change to the existing logic such that we can to pick up queries from paths relative to both the `CARGO_MANIFEST_DIR` (i.e. the crate's `Cargo.toml` file), as well as the workspace root of a given cargo project (i.e. where the workspace's `Cargo.toml` resides).

# Motivation for this change
Under the current implementation as of 0.1.4 (https://github.com/mbuczko/hugsqlx/commit/56f15d300cab6b128c03b4b8acd6f30dff5fe424). A cargo workspace with nested crates who uses `CARGO_MANIFEST_DIR` will need to define a path from the workspace root up to `CARGO_MANIFEST_DIR`.

In this minimal example here: https://github.com/lohvht/test-hugsqlx/blob/main/crates/test-hugsqlx-crate/src/main.rs#L4, the compilation will fail as the `queries` path is assumed to originate via an implicit canonical path (usually assumed to be the workspace root), while `CARGO_MANIFEST_DIR` resolves to the inner crate's `Cargo.toml` directory, thus resulting in the following error.

```
Queries path must be relative to Cargo.toml location (/home/XXX/test-hugsqlx/crates
/test-hugsqlx-crate)
```

Which the easy fix is to move the `test.sql` file inside the nested crate directory. i.e.

```
#[queries = "crates/test-hugsqlx-crate/test.sql"]
```

The existing flow works well with a single crate repo but when extended to workspaces, leads to longer path definitions and a slightly more confusing error message as it currently doesn't take in account that a rust workspace could have multiple `Cargo.toml`

# Proposed changes
try finding the queries file/directory exists within `CARGO_MANIFEST_DIR` first, then the workspace root. If both are exhausted, panic with a similar error message `Queries path must be relative to the crate's Cargo.toml location`, otherwise, the first one that exists will be picked as the SQL file / directory with SQL files to be parsed.

**Comment by mbuczko** [comment]
Change merged in 2982f2e9de451b6deb6fe09f835ad52b06007bde.
