### ISSUE TITLE
Compile errors due to missing lifetime parameters in generated `stream` methods 

### ISSUE THREAD

**Issue by lohvht** [mbuczko/hugsqlx#8]
Hi! as the title suggests, several of the generated methods related mainly to streaming methods i.e. functions annotated with `:^` result in compile errors related to missing lifetimes.

Here are the relevant sections of my Cargo.toml
```toml
[dependencies]
hugsqlx = { version="0.2.1", features = [ "mysql"] }
sqlx = { version = "0.7.2", features = ["mysql", "runtime-tokio-rustls"] }
tokio = { version = "1", features = ["full"]}
```

Here is are 2 separate example queries that can to reproduce the following error on all 3 current targets, `mysql`, `sqlite` and `postgres`:
```sql
-- :name typed_get_stream_users_by_name     :typed :^
SELECT * FROM users WHERE name LIKE ?;
-- :name mapped_get_stream_users_by_name     :mapped :^
SELECT * FROM users WHERE name LIKE ?;
```

The following code produces the following error
```text
error[E0309]: the parameter type `E` may not live long enough
  --> examples/mysql-example/src/main.rs:14:10
   |
14 | #[derive(HugSqlx)]
   |          ^^^^^^^
   |          |
   |          the parameter type `E` must be valid for the lifetime `'e` as defined here...
   |          ...so that the type `E` will meet its required lifetime bounds
   |
   = note: this error originates in the derive macro `HugSqlx` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider adding an explicit lifetime bound
   |
14 | #[derive(HugSqlx: 'e)]
   |                 ++++
```

Tracing the above by the expanded code, it appears that the following lines over `generate_mapped_fn` and `generate_typed_fn` are missing the `+ 'e` lifetime over the parameter `E`.
- `generate_mapped_fn`: https://github.com/mbuczko/hugsqlx/blob/master/hugsqlx-core/src/lib.rs#L291
- `generate_typed_fn`: https://github.com/mbuczko/hugsqlx/blob/master/hugsqlx-core/src/lib.rs#L183

In addition to the 2 queries above, the query below will also generate a separate set of errors related to `sqlite`'s `SqliteArguments` lifetime parameter.
```sql
-- :name untyped_get_stream_users_by_name   :^
SELECT * FROM users WHERE name LIKE ?;
```

```text
error[E0621]: explicit lifetime required in the type of `params`
   --> examples/mysql-example/src/main.rs:104:5
    |
100 |           params: sqlx::sqlite::SqliteArguments<'_>,
    |                   --------------------------------- help: add explicit lifetime `'e` to the type of `params`: `sqlx::sqlx_sqlite::SqliteArguments<'e>`
...
104 | /     {
105 | |         sqlx::query_with("SELECT * FROM users WHERE name LIKE ?;", params).fetch(conn)
106 | |     }
    | |_____^ lifetime `'e` required

```

## Proposed fixes
It should be an easy fix to add the `+ 'e` lifetime params over `E`, however, I am proposing that we should align the lifetimes of the generated methods with `sqlx`'s implementation, i.e. follow the `sqlx` lifetime parameters for the functions that the generated  `hugsqlx` methods use, such as query functions like `query_with` and `query_as_with`, as well as execution functions such as `fetch`, `fetch_optional` etc,

The source codes for those functions are located here:
- https://github.com/launchbadge/sqlx/blob/v0.7.3/sqlx-core/src/query.rs#L147
- https://github.com/launchbadge/sqlx/blob/v0.7.3/sqlx-core/src/query_as.rs#L171

Let me know what do you think of the above? I don't mind taking a stab at this if you're okay with it.

**Comment by lohvht** [comment]
As an example of the above, one of the changes will as follows:
 `E: sqlx::Executor<'e, Database = #db>` will be changed to `E: sqlx::Executor<'c, Database = #db> + 'e`, where `'c: 'e`, i.e. lifetime `'c` is at least as long as `'e`

**Comment by mbuczko** [comment]
> however, I am proposing that we should align the lifetimes of the generated methods with sqlx's implementation

totally agree. I was trying to mess around with lifetimes as you suggested, though still no success. If you have anything working already, I'd be grateful for PR.
Otherwise, I'll spend some more time on this today evening.
